package com.poyi.watchintervals.phone.connection;

public enum ConnectionState {
    UNPAIRED, BLUETOOTH_DISABLED, IDLE, SCANNING, CONNECTING_BLE,
    DISCOVERING_SERVICES, SUBSCRIBING, AUTHENTICATING, CONNECTED_BLE,
    CONNECTED_BLE_LAN, CONNECTED_LAN, SYNCING, DEGRADED_BLE, DISCONNECTED, BACKOFF
}
